name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        shell: bash -l {0}
    name: Linux py ${{ matrix.python-version }} tests
    steps:
    - uses: actions/checkout@v2
    - run: |
        set -e
        wget -O "${HOME}/mambaforge.sh" "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        bash "${HOME}/mambaforge.sh" -b -p "${HOME}/conda"
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda env create --file environment.yml --name bioemu
        conda activate bioemu
        uv pip install -e .
        uv pip install pytest pre-commit
      name: set environment
    - run: |
        set -e
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda activate bioemu
        pre-commit run --all-files
      name: check style
    - run: |
        set -e
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda activate bioemu
        pytest tests/
      name: run tests
